### PR TITLE
Login Screen

### LINKED ISSUE #6: Create Login Screen
Similar to (https://search.muz.li/ZDEwYTFjMWNj).
Incorrect credentials.
Redirect to Gym Details Screen if the credentials are correct.

### PR DESCRIPTION
**Pull request by FirescuOvidiu**
[Issue:6](https://github.com/FirescuOvidiu/Gym-Application/issues/6)
loginScreen

### CODE REVIEW

File: Frontend/src/screens/loginScreen.js [hunk 1]
```diff
@@ -36,38 +43,117 @@ const LoginScreen = ({navigation}) => {
...
+          <Text style={styles.textBeforeTextInput}>Password</Text>
+          <TextInput
+            style={styles.textInput}
+            onChangeText={(UserPassword) => setUserPassword(UserPassword)}
+            placeholder="Enter Password"
+            placeholderTextColor="#6da7f2"
+            blurOnSubmit={false}
+            returnKeyType="next"
+            secureTextEntry={true}
+          />
```
Comment (RaduAlbastroiu) [inline Frontend/src/screens/loginScreen.js:61]: Can email and password be reused for register as well if you split only this part in another component?

**Review by RaduAlbastroiu — CHANGES_REQUESTED** [review]

File: Frontend/src/screens/loginScreen.js (hunk 1 above)
Comment (FirescuOvidiu) [reply Frontend/src/screens/loginScreen.js:61]: Yes, I can make a new component that contains only the email and password and reuse it for register as well.

File: Frontend/package.json [hunk 2]
```diff
@@ -31,7 +31,7 @@
     "babel-jest": "25.5.1",
     "eslint": "6.8.0",
     "jest": "25.5.4",
-    "metro-react-native-babel-preset": "0.59.0",
+    "metro-react-native-babel-preset": "0.51.0",
```
Comment (RaduAlbastroiu) [inline Frontend/package.json]: React native update to 0.64 and metro downgraded? Is this an intended change, does it break anything?

File: Frontend/src/components/authInputField.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+  returnKeyType = 'next',
+  blurOnSubmit = false,
+  secureTextEntry = false,
+}) => {
+  return (
+    <View>
+      <Text style={styles.textBeforeTextInput}>{title}</Text>
+      <TextInput
+        style={styles.textInput}
+        onChangeText={(UserData) => setData(UserData)}
```
Comment (RaduAlbastroiu) [inline Frontend/src/components/authInputField.js]: onChangeText={setData}
It will call setData with a parameter so there is no need to do (userData) => setData(userData)

**Review by RaduAlbastroiu — APPROVED** [review]
